# Generated by Django 4.2.9 on 2024-12-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risco', '0002_maquinaria_reserva_orden_direccionenvio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risco.productos')),
            ],
        ),
    ]
